using System;
using System.IO;
using UnrealBuildTool;

public class UE_Assimp : ModuleRules
{
    public UE_Assimp(ReadOnlyTargetRules Target) : base(Target)
    {
        PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;

        PublicDependencyModuleNames.AddRange(new[]
        {
            "Core",
            "GeometryCore",
            "GeometryFramework",
            "GeometryScriptingCore",
            // If other modules include <assimp/...> directly, we expose headers below.
        });

        PrivateDependencyModuleNames.AddRange(new[]
        {
            "CoreUObject",
            "Engine",
            "Slate",
            "SlateCore",
            "ProceduralMeshComponent",
            "Projects",
            "MeshDescription",
            "MeshConversion",
            "StaticMeshDescription",
        });

        // --- Resolve plugin root without using "../" ---
        // ModuleDirectory = .../Plugins/UE4_Assimp/Source/UE_Assimp
        DirectoryInfo? moduleDir = new DirectoryInfo(ModuleDirectory);
        DirectoryInfo? sourceDir = moduleDir?.Parent;       // .../Source
        DirectoryInfo? pluginDir = sourceDir?.Parent;       // .../Plugins/UE4_Assimp
        if (pluginDir == null)
        {
            throw new BuildException($"Failed to resolve plugin root from ModuleDirectory: {ModuleDirectory}");
        }

        // Primary (your working) layout under Source/ThirdParty/...
        string thirdPartyRootA = Path.Combine(pluginDir.FullName, "Source", "ThirdParty", "UE_AssimpLibrary", "assimp");
        // Optional fallback: module-local ThirdParty layout (kept for flexibility)
        string thirdPartyRootB = Path.Combine(ModuleDirectory, "ThirdParty", "UE_AssimpLibrary", "assimp");

        string assimpRoot = Directory.Exists(thirdPartyRootA) ? thirdPartyRootA :
                            Directory.Exists(thirdPartyRootB) ? thirdPartyRootB :
                            throw new BuildException(
                                $"Assimp payload not found.\n  Tried:\n   {thirdPartyRootA}\n   {thirdPartyRootB}");

        // We want to #include "assimp/scene.h", so the include path must be .../include (not include/assimp)
        string includeRoot      = Path.Combine(assimpRoot, "include");
        string assimpFolder     = Path.Combine(includeRoot, "assimp");
        string versionHeader    = Path.Combine(assimpFolder, "version.h");
        string configHeader     = Path.Combine(assimpFolder, "config.h");    // generated by CMake
        string revisionHeader   = Path.Combine(assimpFolder, "revision.h");  // generated by CMake

        if (!Directory.Exists(assimpFolder))
            throw new BuildException($"Assimp headers missing: {assimpFolder}");
        if (!File.Exists(versionHeader))
            throw new BuildException($"Missing header: {versionHeader}");
        if (!File.Exists(configHeader) || !File.Exists(revisionHeader))
            throw new BuildException($"Generated headers missing. Make sure you copied build-*/include into {includeRoot} (need config.h & revision.h).");

        // Expose headers to any consumer that includes <assimp/...>
        PublicSystemIncludePaths.Add(includeRoot);

        if (Target.Platform == UnrealTargetPlatform.Win64)
        {
            string libDir = Path.Combine(assimpRoot, "lib", "Win64");
            string binDir = Path.Combine(assimpRoot, "bin", "Win64");
            if (!Directory.Exists(libDir)) throw new BuildException($"Assimp lib dir not found: {libDir}");
            if (!Directory.Exists(binDir)) throw new BuildException($"Assimp bin dir not found: {binDir}");

            string[] libs = Directory.GetFiles(libDir, "assimp*.lib", SearchOption.TopDirectoryOnly);
            string[] dlls = Directory.GetFiles(binDir, "assimp*.dll", SearchOption.TopDirectoryOnly);
            if (libs.Length == 0) throw new BuildException($"No assimp .lib in {libDir}");
            if (dlls.Length == 0) throw new BuildException($"No assimp .dll in {binDir}");

            string importLib = libs[0];
            string dllPath   = dlls[0];
            string dllName   = Path.GetFileName(dllPath);

            PublicAdditionalLibraries.Add(importLib);
            PublicDelayLoadDLLs.Add(dllName); // delay-load by filename

            // Stage for packaged builds and for Editor runs
            RuntimeDependencies.Add("$(TargetOutputDir)/"  + dllName, dllPath);
            RuntimeDependencies.Add("$(BinaryOutputDir)/"  + dllName, dllPath);
            if (Target.bBuildEditor)
            {
                // Ensures delay-load resolves in editor when running from Engine/Binaries/Win64
                RuntimeDependencies.Add("$(EngineDir)/Binaries/Win64/" + dllName, dllPath);
            }
        }
        else if (Target.Platform == UnrealTargetPlatform.Mac)
        {
            string macLibDir = Path.Combine(assimpRoot, "lib", "Mac");
            if (!Directory.Exists(macLibDir)) throw new BuildException($"Assimp mac lib dir not found: {macLibDir}");

            string[] dylibs = Directory.GetFiles(macLibDir, "libassimp*.dylib", SearchOption.TopDirectoryOnly);
            if (dylibs.Length == 0)
            {
                throw new BuildException($"No libassimp*.dylib found in {macLibDir}. Did you copy build-mac/bin/Release/libassimp*.dylib -> lib/Mac?");
            }

            string dylibPath = dylibs[0];
            string dylibName = Path.GetFileName(dylibPath);

            // Link directly against the dylib path
            PublicAdditionalLibraries.Add(dylibPath);

            // Stage the dylib alongside the app’s MacOS binary
            RuntimeDependencies.Add("$(TargetOutputDir)/" + dylibName, dylibPath);
            // Also place next to module output so Editor runs are happy
            RuntimeDependencies.Add("$(BinaryOutputDir)/" + dylibName, dylibPath);

            // Note: our CMake cmd sets install_name to @rpath; UE adds standard rpaths,
            // so the loader will resolve this at runtime.
        }
        else if (Target.Platform == UnrealTargetPlatform.Linux)
        {
            string soPath = Path.Combine(assimpRoot, "lib", "Linux", "libassimp.so");
            if (File.Exists(soPath))
            {
                PublicAdditionalLibraries.Add(soPath);
                RuntimeDependencies.Add("$(TargetOutputDir)/libassimp.so", soPath);
            }
        }
    }
}