// Copyright (c) 2025 ProjectMobius contributors. Licensed under MIT.

#include "Hdf5DataExampleTest.h"
#include "Hdf5SimulationReader.h"

#include "Interfaces/IPluginManager.h"
#include "Misc/Paths.h"

#include "hdf5.h"

DEFINE_LOG_CATEGORY_STATIC(LogHdf5DataExampleTest, Log, All);

namespace
{
	herr_t LogLinkCallback(hid_t group, const char* name, const H5L_info_t* info, void* opData)
	{
		UE_LOG(LogHdf5DataExampleTest, Log, TEXT("HDF5 entry: %hs"), name);
		UE_LOG(LogHdf5DataExampleTest, Warning, TEXT("HDF5 link type: %d"), info->type);
		return 0;
	}
}

void FHdf5DataExampleTest::RunExampleFile()
{
	const TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("MobiusDataImporter"));
	if (!Plugin.IsValid())
	{
		UE_LOG(LogHdf5DataExampleTest, Error, TEXT("MobiusDataImporter not found."));
		return;
	}

	const FString ExamplePath = FPaths::Combine(
		Plugin->GetBaseDir(),
		TEXT("Source"),
		TEXT("ThirdParty"),
		TEXT("hdf5-2.0.0"),
		TEXT("HDF5Examples"),
		TEXT("C"),
		TEXT("H5G"),
		TEXT("h5ex_g_iterate.h5"));

	if (!FPaths::FileExists(ExamplePath))
	{
		UE_LOG(LogHdf5DataExampleTest, Warning, TEXT("Example HDF5 file not found: %s"), *ExamplePath);
		return;
	}

	FTCHARToUTF8 ExamplePathUtf8(*ExamplePath);

	H5open();

	const hid_t FileId = H5Fopen(ExamplePathUtf8.Get(), H5F_ACC_RDONLY, H5P_DEFAULT);
	if (FileId < 0)
	{
		UE_LOG(LogHdf5DataExampleTest, Error, TEXT("Failed to open HDF5 file: %s"), *ExamplePath);
		H5close();
		return;
	}

	UE_LOG(LogHdf5DataExampleTest, Log, TEXT("Opened HDF5 file: %s"), *ExamplePath);

	hsize_t Index = 0;
	const herr_t IterateStatus = H5Literate(FileId, H5_INDEX_NAME, H5_ITER_NATIVE, &Index, &LogLinkCallback, nullptr);
	if (IterateStatus < 0)
	{
		UE_LOG(LogHdf5DataExampleTest, Error, TEXT("Failed to iterate HDF5 root links for: %s"), *ExamplePath);
	}

	H5Fclose(FileId);
	H5close();
}

void FHdf5DataExampleTest::TestSimulationReader()
{
	UE_LOG(LogHdf5DataExampleTest, Log, TEXT("=== Testing FHdf5SimulationReader ==="));

	const TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("MobiusDataImporter"));
	if (!Plugin.IsValid())
	{
		UE_LOG(LogHdf5DataExampleTest, Error, TEXT("MobiusDataImporter not found."));
		return;
	}

	// Path to test file generated by json_to_hdf5_converter.py
	const FString TestFilePath = FPaths::Combine(
		Plugin->GetBaseDir(),
		TEXT("TestData"),
		TEXT("iso-test-1.h5"));

	if (!FPaths::FileExists(TestFilePath))
	{
		UE_LOG(LogHdf5DataExampleTest, Warning, TEXT("Test simulation HDF5 file not found: %s"), *TestFilePath);
		UE_LOG(LogHdf5DataExampleTest, Warning, TEXT("Run the Python converter script to generate it:"));
		UE_LOG(LogHdf5DataExampleTest, Warning, TEXT("  python Scripts/json_to_hdf5_converter.py <input.json> TestData/iso-test-1.h5"));
		return;
	}

	// Check if valid simulation file
	if (!FHdf5SimulationReader::IsValidSimulationFile(TestFilePath))
	{
		UE_LOG(LogHdf5DataExampleTest, Error, TEXT("File is not a valid simulation HDF5 file: %s"), *TestFilePath);
		return;
	}

	UE_LOG(LogHdf5DataExampleTest, Log, TEXT("File validated as simulation HDF5: %s"), *TestFilePath);

	// Create reader and open file
	FHdf5SimulationReader Reader;
	if (!Reader.OpenFile(TestFilePath))
	{
		UE_LOG(LogHdf5DataExampleTest, Error, TEXT("Failed to open simulation file"));
		return;
	}

	// Read metadata
	FHdf5SimulationMetadata Metadata;
	if (Reader.ReadMetadata(Metadata))
	{
		UE_LOG(LogHdf5DataExampleTest, Log, TEXT("Metadata:"));
		UE_LOG(LogHdf5DataExampleTest, Log, TEXT("  Duration: %.2f seconds"), Metadata.Duration);
		UE_LOG(LogHdf5DataExampleTest, Log, TEXT("  Sampling Rate: %.2f"), Metadata.SamplingRate);
		UE_LOG(LogHdf5DataExampleTest, Log, TEXT("  Max Entities: %d"), Metadata.MaxNumEntities);
		UE_LOG(LogHdf5DataExampleTest, Log, TEXT("  Is SI: %s"), Metadata.bIsSI ? TEXT("true") : TEXT("false"));
		UE_LOG(LogHdf5DataExampleTest, Log, TEXT("  Is Degrees: %s"), Metadata.bIsDeg ? TEXT("true") : TEXT("false"));
	}

	// Read entities
	TArray<FHdf5EntityData> Entities;
	if (Reader.ReadEntities(Entities))
	{
		UE_LOG(LogHdf5DataExampleTest, Log, TEXT("Entities (%d total):"), Entities.Num());
		// Log first 3 entities as sample
		int32 LogCount = FMath::Min(3, Entities.Num());
		for (int32 i = 0; i < LogCount; ++i)
		{
			UE_LOG(LogHdf5DataExampleTest, Log, TEXT("  [%d] ID=%d, Name='%s', MaxSpeed=%.4f"),
				i, Entities[i].Id, *Entities[i].Name, Entities[i].MaxSpeed);
		}
		if (Entities.Num() > 3)
		{
			UE_LOG(LogHdf5DataExampleTest, Log, TEXT("  ... and %d more"), Entities.Num() - 3);
		}
	}

	// Read timesteps
	TArray<float> Timesteps;
	if (Reader.ReadTimesteps(Timesteps))
	{
		UE_LOG(LogHdf5DataExampleTest, Log, TEXT("Timesteps (%d total):"), Timesteps.Num());
		if (Timesteps.Num() > 0)
		{
			UE_LOG(LogHdf5DataExampleTest, Log, TEXT("  First: %.2f, Last: %.2f"),
				Timesteps[0], Timesteps.Last());
		}
	}

	// Read samples per timestep
	TArray<int32> SamplesPerTimestep;
	if (Reader.ReadSamplesPerTimestep(SamplesPerTimestep))
	{
		int32 TotalSamples = 0;
		for (int32 Count : SamplesPerTimestep)
		{
			TotalSamples += Count;
		}
		UE_LOG(LogHdf5DataExampleTest, Log, TEXT("Samples per timestep: %d timesteps, %d total samples"),
			SamplesPerTimestep.Num(), TotalSamples);
	}

	// Read first few samples to verify data
	TArray<FHdf5SampleData> FirstSamples;
	if (Reader.ReadSamplesForTimestepRange(0, 0, FirstSamples))
	{
		UE_LOG(LogHdf5DataExampleTest, Log, TEXT("First timestep samples (%d):"), FirstSamples.Num());
		int32 LogCount = FMath::Min(3, FirstSamples.Num());
		for (int32 i = 0; i < LogCount; ++i)
		{
			const FHdf5SampleData& S = FirstSamples[i];
			UE_LOG(LogHdf5DataExampleTest, Log, TEXT("  Entity %d: Pos=(%.2f, %.2f, %.2f), Rot=%.2f, Speed=%.4f"),
				S.EntityId, S.PositionX, S.PositionY, S.PositionZ, S.Rotation, S.Speed);
		}
	}

	Reader.CloseFile();
	UE_LOG(LogHdf5DataExampleTest, Log, TEXT("=== FHdf5SimulationReader test complete ==="));
}
